CREATE TABLE IF NOT EXISTS Users (
    id CHAR(21) PRIMARY KEY,
    googleId VARCHAR(255) NOT NULL,
    givenName VARCHAR(255) NOT NULL,
    surName VARCHAR(255) NOT NULL,
    secondSurName VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    pfp VARCHAR(255) NULL,
    gender INT,
    birthday DATE,
    countryCode VARCHAR(10),
    phoneNumber VARCHAR(20),
    nationality INT,
    occupation INT,
    placeOfWork VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (gender) REFERENCES Gender(id) ON DELETE CASCADE,
    FOREIGN KEY (nationality) REFERENCES Nationality(id) ON DELETE CASCADE,
    FOREIGN KEY (occupation) REFERENCES Occupation(id) ON DELETE CASCADE,
);

CREATE TABLE Nationality (
    id INT AUTO_INCREMENT PRIMARY KEY,
    countryName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Occupation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    occupationName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Gender (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sex CHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS HouseRules (
    id TINYINT PRIMARY KEY AUTO_INCREMENT, 
    ruleName VARCHAR(255) UNIQUE NOT NULL,
    icon VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Amenities (
    id TINYINT PRIMARY KEY AUTO_INCREMENT,
    amenityName VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS AmenitiesTypes (
    id TINYINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS BedroomAmenities (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(100) UNIQUE NOT NULL,
    icon VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ListingTypes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Currencies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code CHAR(3) NOT NULL UNIQUE,
    symbol VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS Listing (
    id CHAR(21) PRIMARY KEY,
    userId CHAR(21) NOT NULL,
    title VARCHAR(255) UNIQUE NOT NULL,
    monthlyRent DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    currencyId INT NOT NULL,
    description VARCHAR(1000),
    bedrooms TINYINT UNSIGNED DEFAULT 0,
    beds TINYINT UNSIGNED DEFAULT 1,
    bathrooms DECIMAL(3,1) UNSIGNED DEFAULT 0.0,
    roomAreaSqM DECIMAL(6,2) UNSIGNED DEFAULT 0.00,
    placeAreaSqM DECIMAL(6,2) UNSIGNED DEFAULT 0.00,
    minimumStayDays INT UNSIGNED DEFAULT 0,
    maxStayDays INT UNSIGNED DEFAULT 0,
    listingTypeId INT NOT NULL,
    peopleAllowed TINYINT UNSIGNED DEFAULT 1,
    isChecked BOOLEAN DEFAULT FALSE,
    isActive BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (listingTypeId) REFERENCES ListingTypes(id) ON DELETE CASCADE,
    FOREIGN KEY (currencyId) REFERENCES Currencies(id)
);

CREATE TABLE IF NOT EXISTS Address (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) UNIQUE NOT NULL,
    streetAddress VARCHAR(255),
    houseNumber VARCHAR(50),
    postalCode VARCHAR(20) NOT NULL,
    city VARCHAR(100),
    stateOrProvince VARCHAR(100),
    countryCode CHAR(2) NOT NULL, 
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    extraInfo TEXT,

    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListingBedroomAmenities (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,
    bedroomAmenityId INT NOT NULL,

    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE,
    FOREIGN KEY (bedroomAmenityId) REFERENCES BedroomAmenities(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListingHouseRules (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,
    ruleId TINYINT NOT NULL,
    isAllowed BOOLEAN NOT NULL,
    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE,
    FOREIGN KEY (ruleId) REFERENCES HouseRules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListingAmenities (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,
    amenityTypeId TINYINT NOT NULL,
    roomNumber INT NULL,
    amenityId TINYINT NOT NULL,

    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE,
    FOREIGN KEY (amenityTypeId) REFERENCES AmenitiesTypes(id) ON DELETE CASCADE,
    FOREIGN KEY (amenityId) REFERENCES Amenities(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListingAvailability (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    isAvailable BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListingRestrictions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,            
    maxTenants TINYINT UNSIGNED NOT NULL,     
    extraCostPerTenant DECIMAL(10,2) DEFAULT 0.00, 
    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Utility (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,
    waterIncluded BOOLEAN DEFAULT FALSE,
    electricIncluded BOOLEAN DEFAULT FALSE,
    gasIncluded BOOLEAN DEFAULT FALSE,
    internetIncluded BOOLEAN DEFAULT FALSE,
    cleaningIncluded BOOLEAN DEFAULT FALSE,
    cleaningFee INT NULL,
    
	FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListingPhotos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,   
    url VARCHAR(255) NOT NULL,  
    isPrimary BOOLEAN DEFAULT FALSE,
    amenityTypeId TINYINT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE,
    FOREIGN KEY (amenityTypeId) REFERENCES AmenitiesTypes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BookingStatuses (
    id TINYINT PRIMARY KEY AUTO_INCREMENT,
    statusName VARCHAR(50) UNIQUE NOT NULL 
);

CREATE TABLE IF NOT EXISTS Bookings (
    id CHAR(21) PRIMARY KEY,
    listingId CHAR(21) NOT NULL,
    hostId CHAR(21) NOT NULL,
    guestId CHAR(21) NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    statusId TINYINT DEFAULT 6,
    additionalInfo TEXT, 
    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE,
    FOREIGN KEY (hostId) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (guestId) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (statusId) REFERENCES BookingStatuses(id) ON DELETE SET NULL
);



CREATE TABLE IF NOT EXISTS ListingHostInfo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    listingId CHAR(21) NOT NULL,
    livesInProperty BOOLEAN DEFAULT FALSE,
    hostGender  BOOLEAN DEFAULT FALSE,
    hostAgeRange ENUM('18-25 years', '26-30 years', '31-40 years', '41+ years'),
    livesWithFamily BOOLEAN DEFAULT FALSE,
    hasPets BOOLEAN DEFAULT FALSE,
    isVerified BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    genderAllowedId INT,
    peopleHosted INT DEFAULT 0,
    userId CHAR(21) NOT NULL,
    FOREIGN KEY (listingId) REFERENCES Listing(id) ON DELETE CASCADE,
    FOREIGN KEY (genderAllowedId) REFERENCES Gender(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Landlords (
    userId CHAR(21) PRIMARY KEY,
    rating DECIMAL(3,2) DEFAULT 0.0,
    responseTimeMinutes INT DEFAULT NULL,
    verified BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS 