SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ListingHostInfo;
DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS BookingStatuses;
DROP TABLE IF EXISTS ListingPhotos;
DROP TABLE IF EXISTS PhotoTypes;
DROP TABLE IF EXISTS ListingRestrictions;
DROP TABLE IF EXISTS ListingAvailability;
DROP TABLE IF EXISTS ListingAmenities;
DROP TABLE IF EXISTS ListingHouseRules;
DROP TABLE IF EXISTS ListingBedroomAmenities;
DROP TABLE IF EXISTS Listing;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS HouseRules;
DROP TABLE IF EXISTS Amenities;
DROP TABLE IF EXISTS BedroomAmenities;
DROP TABLE IF EXISTS Utilities;
DROP TABLE IF EXISTS AmenitiesTypes;
DROP TABLE IF EXISTS Gender;
DROP TABLE IF EXISTS Currencies;
DROP TABLE IF EXISTS ListingTypes;

SET FOREIGN_KEY_CHECKS = 1;
