INSERT INTO HouseRules (ruleName, icon) VALUES 
('Smoking Allowed', '/smoking.png'),
('Pets Allowed', '/pets.png'),
('Overnight Guests Allowed', '/guests.png'),
('City Hall Registration Supported', '/registration.png'),
('Couples Allowed', '/couples.png');

INSERT INTO AmenitiesTypes (name) VALUES 
('Kitchen'),
('Living Room'),
('Bathroom'),
('Dining Room'),
('Balcony'),
('Bedroom'),
('Exterior'),
('Other');

INSERT INTO Amenities (amenityName) VALUES
('Wi-Fi'),
('Cable TV'),
('Central heating'),
('Elevator'),
('Window'),
('Fridge'),
('Freezer'),
('Stove'),
('Oven'),
('Microwave'),
('Washing machine'),
('Dishes and cutlery'),
('Pots and pans'),
('Toilet'),
('Sink'),
('Shower'),
('Bathtub'),
('Sofa'),
('Coffee table'),
('TV'),
('Sofa bed'),
('Chairs'),
('Table'),
('Bed linen and towels'),
('Accessibility'),
('Air conditioning');


INSERT INTO BedroomAmenities (name, icon) VALUES
('Wardrobe', '/wardrobe.png'),
('Desk/Table', '/desk.png'),
('Chairs', '/office_chair.png'),
('Sofa bed', '/sofa.png'),
('Window', '/window.png'),
('Balcony', '/balcony.png'),
('Double bed', '/bed.png'),
('Single bed', '/bed.png'),
('Bunk bed', '/bunk_bed.png'),
('Air conditioning', NULL);

INSERT INTO BookingStatuses (statusName) 
VALUES ('pending'), ('confirmed'), ('cancelled'), ('completed'), ('declined'), ('created'), ('ongoing');

INSERT INTO Gender (sex) VALUES
('Mixed Gender'),
('Males'),
('Females');

INSERT INTO Currencies (code, symbol) VALUES
('USD', '$'),
('EUR', '€'),
('GBP', '£'),
('JPY', '¥');

INSERT INTO ListingTypes (name) VALUES 
('Apartment'),
('Studio'),
('Private Room'),
('Shared Room');


INSERT INTO Nationality (countryName) VALUES
('Afghanistan'),
('Åland Islands'),
('Albania'),
('Algeria'),
('American Samoa'),
('Andorra'),
('Angola'),
('Anguilla'),
('Antarctica'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Aruba'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bermuda'),
('Bhutan'),
('Bolivia'),
('Bonaire, Sint Eustatius and Saba'),
('Bosnia and Herzegovina'),
('Botswana'),
('Bouvet Island'),
('Brazil'),
('British Indian Ocean Territory'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cabo Verde'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cayman Islands'),
('Central African Republic'),
('Chile'),
('China'),
('Christmas Island'),
('Cocos (Keeling) Islands'),
('Colombia'),
('Comoros'),
('Congo, Republic of the'),
('Congo, the Democratic Republic of the'),
('Cook Islands'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Curaçao'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Falkland Islands (Malvinas)'),
('Faroe Islands'),
('Fiji'),
('Finland'),
('France'),
('French Guiana'),
('French Polynesia'),
('French Southern Territories'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Gibraltar'),
('Greece'),
('Greenland'),
('Grenada'),
('Guadeloupe'),
('Guam'),
('Guatemala'),
('Guernsey'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Heard Island and McDonald Islands'),
('Holy See (Vatican City State)'),
('Honduras'),
('Hong Kong'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Isle of Man'),
('Israel'),
('Italy'),
('Ivory Coast'),
('Jamaica'),
('Japan'),
('Jersey'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Korea, Democratic Peoples Republic of'),
('Korea, Republic of'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macao'),
('Macedonia (FYROM)'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Martinique'),
('Mauritania'),
('Mauritius'),
('Mayotte'),
('Mexico'),
('Micronesia, Federated States of'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Montserrat'),
('Morocco'),
('Mozambique'),
('Myanmar'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('Netherlands Antilles'),
('New Caledonia'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Niue'),
('Norfolk Island'),
('Northern Mariana Islands'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Palestine, State of'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Pitcairn'),
('Poland'),
('Portugal'),
('Puerto Rico'),
('Qatar'),
('Reunion Island'),
('Romania'),
('Russian Federation'),
('Rwanda'),
('Saint Barthélémy'),
('Saint Helena, Ascension and Tristan da Cunha'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Martin (French part)'),
('Saint Pierre and Miquelon'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Sint Maarten (Dutch part)'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Georgia and the South Sandwich Islands'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Svalbard and Jan Mayen'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syrian Arab Republic'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Timor-Leste'),
('Togo'),
('Tokelau'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Turks and Caicos Islands'),
('Tuvalu'),
('U.S. Virgin Islands'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('United States Minor Outlying Islands'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Virgin Islands, British'),
('Wallis and Futuna'),
('Western Sahara'),
('Yemen'),
('Zambia'),
('Zimbabwe');


INSERT INTO CountryCallingCodes (countryName, callingCode) VALUES
('Sint Maarten', '+1'),
('St Vincent & the Grenadines', '+1'),
('Grenada', '+1'),
('Dominican Republic', '+1'),
('Anguilla', '+1'),
('Dominica', '+1'),
('US Virgin Islands', '+1'),
('Antigua & Barbuda', '+1'),
('Jamaica', '+1'),
('Puerto Rico', '+1'),
('Montserrat', '+1'),
('American Samoa', '+1'),
('Bermuda', '+1'),
('Turks & Caicos', '+1'),
('Northern Mariana Islands', '+1'),
('United States', '+1'),
('Cayman Islands', '+1'),
('Trinidad & Tobago', '+1'),
('Barbados', '+1'),
('Guam', '+1'),
('St Lucia', '+1'),
('Canada', '+1'),
('British Virgin Islands', '+1'),
('St Kitts & Nevis', '+1'),
('Bahamas', '+1'),
('Russia', '+7'),
('Kazakhstan', '+7'),
('Egypt', '+20'),
('South Africa', '+27'),
('Greece', '+30'),
('Netherlands', '+31'),
('Belgium', '+32'),
('France', '+33'),
('Spain', '+34'),
('Hungary', '+36'),
('Italy', '+39'),
('Romania', '+40'),
('Switzerland', '+41'),
('Austria', '+43'),
('United Kingdom', '+44'),
('Denmark', '+45'),
('Sweden', '+46'),
('Norway', '+47'),
('Poland', '+48'),
('Germany', '+49'),
('Peru', '+51'),
('Mexico', '+52'),
('Cuba', '+53'),
('Argentina', '+54'),
('Brazil', '+55'),
('Chile', '+56'),
('Colombia', '+57'),
('Venezuela', '+58'),
('Malaysia', '+60'),
('Australia', '+61'),
('Indonesia', '+62'),
('Philippines', '+63'),
('New Zealand', '+64'),
('Singapore', '+65'),
('Thailand', '+66'),
('Japan', '+81'),
('South Korea', '+82'),
('Vietnam', '+84'),
('China', '+86'),
('Turkey', '+90'),
('India', '+91'),
('Pakistan', '+92'),
('Afghanistan', '+93'),
('Sri Lanka', '+94'),
('Myanmar', '+95'),
('Iran', '+98'),
('South Sudan', '+211'),
('Western Sahara', '+212'),
('Morocco', '+212'),
('Algeria', '+213'),
('Tunisia', '+216'),
('Libya', '+218'),
('Gambia', '+220'),
('Senegal', '+221'),
('Mauritania', '+222'),
('Mali', '+223'),
('Guinea', '+224'),
('Ivory Coast', '+225'),
('Burkina Faso', '+226'),
('Niger', '+227'),
('Togo', '+228'),
('Benin', '+229'),
('Mauritius', '+230'),
('Liberia', '+231'),
('Sierra Leone', '+232'),
('Ghana', '+233'),
('Nigeria', '+234'),
('Chad', '+235'),
('Central African Republic', '+236'),
('Cameroon', '+237'),
('Cape Verde', '+238'),
('São Tomé and Príncipe', '+239'),
('Equatorial Guinea', '+240'),
('Gabon', '+241'),
('Congo', '+242'),
('Democratic Republic of the Congo', '+243'),
('Angola', '+244'),
('Guinea-Bissau', '+245'),
('British Indian Ocean Territory', '+246'),
('Ascension Island', '+247'),
('Seychelles', '+248'),
('Sudan', '+249'),
('Rwanda', '+250'),
('Ethiopia', '+251'),
('Djibouti', '+253'),
('Kenya', '+254'),
('Tanzania', '+255'),
('Uganda', '+256'),
('Burundi', '+257'),
('Mozambique', '+258'),
('Zambia', '+260'),
('Madagascar', '+261'),
('Réunion', '+262'),
('Zimbabwe', '+263'),
('Namibia', '+264'),
('Malawi', '+265'),
('Lesotho', '+266'),
('Botswana', '+267'),
('Swaziland', '+268'),
('Comoros', '+269'),
('Saint Helena and Tristan da Cunha', '+290'),
('Eritrea', '+291'),
('Aruba', '+297'),
('Faroe Islands', '+298'),
('Greenland', '+299'),
('Gibraltar', '+350'),
('Portugal', '+351'),
('Luxembourg', '+352'),
('Ireland', '+353'),
('Iceland', '+354'),
('Albania', '+355'),
('Malta', '+356'),
('Cyprus', '+357'),
('Finland', '+358'),
('Bulgaria', '+359'),
('Lithuania', '+370'),
('Latvia', '+371'),
('Estonia', '+372'),
('Moldova', '+373'),
('Armenia', '+374'),
('Belarus', '+375'),
('Andorra', '+376'),
('Monaco', '+377'),
('San Marino', '+378'),
('Ukraine', '+380'),
('Serbia', '+381'),
('Montenegro', '+382'),
('Kosovo', '+383'),
('Croatia', '+385'),
('Slovenia', '+386'),
('Bosnia-Herzegovina', '+387'),
('Macedonia', '+389'),
('Czech Republic', '+420'),
('Slovakia', '+421'),
('Liechtenstein', '+423'),
('Falkland Islands', '+500'),
('Belize', '+501'),
('Guatemala', '+502'),
('El Salvador', '+503'),
('Honduras', '+504'),
('Nicaragua', '+505'),
('Costa Rica', '+506'),
('Panama', '+507'),
('Saint Pierre and Miquelon', '+508'),
('Haiti', '+509'),
('Guadeloupe', '+590'),
('Bolivia', '+591'),
('Guyana', '+592'),
('Ecuador', '+593'),
('French Guiana', '+594'),
('Paraguay', '+595'),
('Martinique', '+596'),
('Suriname', '+597'),
('Uruguay', '+598'),
('Caribbean Netherlands', '+599'),
('Curaçao', '+599'),
('Timor-Leste', '+670'),
('Australian Antarctic Territory', '+672'),
('Brunei', '+673'),
('Nauru', '+674'),
('Papua New Guinea', '+675'),
('Tonga', '+676'),
('Solomon Islands', '+677'),
('Vanuatu', '+678'),
('Fiji', '+679'),
('Palau', '+680'),
('Wallis and Futuna', '+681'),
('Cook Islands', '+682'),
('Niue', '+683'),
('Samoa', '+685'),
('Kiribati', '+686'),
('New Caledonia', '+687'),
('Tuvalu', '+688'),
('French Polynesia', '+689'),
('Tokelau', '+690'),
('Micronesia', '+691'),
('Marshall Islands', '+692'),
('North Korea', '+850'),
('Hong Kong', '+852'),
('Macau', '+853'),
('Cambodia', '+855'),
('Laos', '+856'),
('Bangladesh', '+880'),
('Taiwan', '+886'),
('Maldives', '+960'),
('Lebanon', '+961'),
('Jordan', '+962'),
('Syria', '+963'),
('Iraq', '+964'),
('Kuwait', '+965'),
('Saudi Arabia', '+966'),
('Yemen', '+967'),
('Oman', '+968'),
('Palestine', '+970'),
('United Arab Emirates', '+971'),
('Israel', '+972'),
('Bahrain', '+973'),
('Qatar', '+974'),
('Bhutan', '+975'),
('Mongolia', '+976'),
('Nepal', '+977'),
('Tajikistan', '+992'),
('Turkmenistan', '+993'),
('Azerbaijan', '+994'),
('Georgia', '+995'),
('Kyrgyzstan', '+996'),
('Uzbekistan', '+998'),


-- New unique IDs
SET @userIdLondon6 = 'usrlnd006abc987xyz321';
SET @listingIdLondon6 = 'lstlnd006xyz321abc987';

-- Create new user (host)
INSERT INTO Users (id, givenName, surName, secondSurName)
VALUES (@userIdLondon6, 'Oliver', 'Smith', NULL);

-- Create the listing
INSERT INTO Listing (
  id, userId, title, monthlyRent, currencyId, description,
  bedrooms, beds, bathrooms, roomAreaSqM, placeAreaSqM,
  minimumStayDays, maxStayDays, listingTypeId, peopleAllowed, isChecked,
  createdAt, updatedAt
) VALUES (
  @listingIdLondon6, @userIdLondon6, 'Bright Camden Flat with Garden Access',
  2200.00, 2,
  'Spacious and well-lit flat in the heart of Camden. Quiet neighborhood with private garden access, ideal for young professionals or couples.',
  2, 2, 1.5, 40.00, 60.00,
  30, 180, 1, 2, TRUE,
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- Address
INSERT INTO Address (
  listingId, streetAddress, houseNumber, postalCode, city,
  stateOrProvince, countryCode, latitude, longitude, extraInfo
) VALUES (
  @listingIdLondon6, 'Camden Road', '121B', 'NW1 9HA', 'London',
  'Greater London', 'GB', 51.5433, -0.1428, 'Private garden access, ground floor'
);

-- House rules
INSERT INTO ListingHouseRules (listingId, ruleId, isAllowed)
VALUES 
  (@listingIdLondon6, 1, FALSE),  -- Smoking
  (@listingIdLondon6, 2, TRUE),   -- Pets
  (@listingIdLondon6, 3, TRUE),   -- Overnight guests
  (@listingIdLondon6, 4, TRUE);   -- City Hall registration supported

-- Amenities
INSERT INTO ListingAmenities (listingId, amenityTypeId, roomNumber, amenityId)
VALUES 
  -- Kitchen
  (@listingIdLondon6, 1, NULL, 6),  -- Fridge
  (@listingIdLondon6, 1, NULL, 8),  -- Stove
  (@listingIdLondon6, 1, NULL, 9),  -- Oven
  (@listingIdLondon6, 1, NULL, 10), -- Microwave
  (@listingIdLondon6, 1, NULL, 11), -- Washing machine
  (@listingIdLondon6, 1, NULL, 13), -- Pots and pans
  
  -- Living Room
  (@listingIdLondon6, 2, NULL, 1),  -- Wi-Fi
  (@listingIdLondon6, 2, NULL, 3),  -- Central heating
  (@listingIdLondon6, 2, NULL, 20), -- Coffee table
  (@listingIdLondon6, 2, NULL, 21), -- TV
  
  -- Bathroom
  (@listingIdLondon6, 3, NULL, 14), -- Toilet
  (@listingIdLondon6, 3, NULL, 15), -- Sink
  (@listingIdLondon6, 3, NULL, 16), -- Shower
  
  -- Balcony/Outdoor
  (@listingIdLondon6, 5, NULL, 25), -- Air conditioning
  (@listingIdLondon6, 5, NULL, 13); -- Balcony

-- Bedroom amenities
INSERT INTO ListingBedroomAmenities (listingId, bedroomAmenityId)
VALUES 
  (@listingIdLondon6, 1),  -- Wardrobe
  (@listingIdLondon6, 2),  -- Desk/Table
  (@listingIdLondon6, 3),  -- Chairs
  (@listingIdLondon6, 7);  -- Double Bed

-- Utilities
INSERT INTO Utility (
  listingId, waterIncluded, electricIncluded, gasIncluded,
  internetIncluded, cleaningIncluded, cleaningFee
) VALUES (
  @listingIdLondon6, TRUE, TRUE, FALSE, TRUE, TRUE, 30
);

-- Restrictions
INSERT INTO ListingRestrictions (
  listingId, maxTenants, extraCostPerTenant
) VALUES (
  @listingIdLondon6, 2, 20.00
);

-- Availability
INSERT INTO ListingAvailability (
  listingId, startDate, endDate, isAvailable
) VALUES (
  @listingIdLondon6, '2025-09-01', '2026-03-01', TRUE
);

-- Host Info
INSERT INTO ListingHostInfo (
  listingId, livesInProperty, hostGender, hostAgeRange,
  livesWithFamily, hasPets, isVerified,
  genderAllowedId, peopleHosted, userId
) VALUES (
  @listingIdLondon6, FALSE, TRUE, '26-30 years',
  FALSE, TRUE, TRUE, 1, 1, @userIdLondon6
);

-- Photos
INSERT INTO ListingPhotos (
  listingId, url, isPrimary, amenityTypeId
) VALUES 
  (@listingIdLondon6, 'https://example.com/photos/camden-flat-garden.jpg', TRUE, 5);

